--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XenoDude/TokenGrabber
build-by-default: true
branches:
- main
projects:
  TokenGrabber:
    path: ""
    model: virion
    type: library
...
